version: "3.8"
services:
  # Nginx service
  nginx:
    image: nginx:alpine
    container_name: mba-nginx
    ports:
      - ${NGINX_LUMEN_AG_PORT}:80
      - ${NGINX_PRODUCT_PORT}:82
      - ${NGINX_QR_BENEFIT_PORT}:83
      - ${NGINX_OPENCART_PORT}:84
      - 1000:1000
      - 2001:2001
    volumes:
      - ./src:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ./logs/nginx/access_log.log:/var/log/nginx/access_log.log
      - ./logs/nginx/error.log:/var/log/nginx/error.log
    networks:
      - mba-lumen-AG
      - apisix

  # PHP service
  api-gateway:
    build: ./docker/api-gateway
    container_name: mba-api-gateway
    working_dir: /var/www/
    volumes:
      - ./src:/var/www
      - ./docker/api-gateway/php-fpm/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./docker/api-gateway/php-fpm/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker/api-gateway/php-fpm/php-fpm.d/www.conf:/usr/local/etc/php-fpm/www.conf
      - ./logs/api-gateway/php-fpm/php-fpm.log:/var/log/php-fpm.log
    networks:
      - mba-lumen-AG

  opencart:
    build: ./docker/opencart
    container_name: mba-opencart
    working_dir: /var/www/
    volumes:
      - ./src:/var/www
      - ./docker/opencart/php-fpm/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./docker/opencart/php-fpm/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker/opencart/php-fpm/php-fpm.d/www.conf:/usr/local/etc/php-fpm/www.conf
      - ./logs/opencart/php-fpm/php-fpm.log:/var/log/php-fpm.log
    networks:
      - mba-lumen-AG

  # MySQL database service
  db:
    image: mysql:5.7
    container_name: mba-db
    ports:
      - "3307:3306"
    command: mysqld --user=root
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    env_file:
      - ./.env
    networks:
      - mba-lumen-AG

  # Cache Redis
  redis:
    image: redis
    container_name: mba-redis
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - mba-lumen-AG

  # GUI Manage MySQL
  adminer:
    image: adminer:latest
    container_name: mba-adminer
    environment:
      ADMINER_DEFAULT_SERVER: db
    ports:
      - ${ADMINER_PORT}:8080
    networks:
      - mba-lumen-AG

  # GUI Manage Docker
  redis-commander:
    container_name: mba-redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "${REDIS_WEB_PORT}:8081"
    networks:
      - mba-lumen-AG

  # Test Mail
  mailhog:
    image: mailhog/mailhog
    container_name: mba-mailhog
    ports:
      - ${MAIL_SMTP_PORT}:1025 # smtp server
      - ${MAIL_WEB_PORT}:8025 # web ui
    networks:
      - mba-lumen-AG

  # RabbitMQ (Message Queue)
  rabbitmq:
    image: rabbitmq:3.8
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASSWORD: guest
      RABBITMQ_DEFAULT_VHOST: /
      RABBITMQ_SSL_CACERTFILE: /rootCA.pem
      RABBITMQ_SSL_CERTFILE: /rootCA.pem
      RABBITMQ_SSL_KEYFILE: /rootCA.key
      RABBITMQ_SSL_VERIFY: verify_none
      RABBITMQ_SSL_FAIL_IF_NO_PEER_CERT: "false"
    volumes:
      - "./keys/rabbitmq/rootCA.pem:/rootCA.pem:ro"
      - "./keys/rabbitmq/rootCA.key:/rootCA.key:ro"
    ports:
      - "${RABBITMQ_15671_PORT}:15671"
      - "${RABBITMQ_15672_PORT}:15672"
      - "${RABBITMQ_5671_PORT}:5671"
      - "${RABBITMQ_5672_PORT}:5672"
    networks:
      - mba-lumen-AG

  # GUI Manage RabbitMQ
  # rabbitmq-management:
  #   image: rabbitmq:management
  #   environment:
  #     RABBITMQ_DEFAULT_USER: guest
  #     RABBITMQ_DEFAULT_PASSWORD: guest
  #     RABBITMQ_DEFAULT_VHOST: /
  #     RABBITMQ_MANAGEMENT_SSL_CACERTFILE: /rootCA.pem
  #     RABBITMQ_MANAGEMENT_SSL_CERTFILE: /rootCA.pem
  #     RABBITMQ_MANAGEMENT_SSL_KEYFILE: /rootCA.key
  #     RABBITMQ_MANAGEMENT_SSL_VERIFY: verify_none
  #     RABBITMQ_MANAGEMENT_SSL_FAIL_IF_NO_PEER_CERT: "false"
  #   volumes:
  #     - "./keys/rabbitmq/rootCA.pem:/rootCA.pem:ro"
  #     - "./keys/rabbitmq/rootCA.key:/rootCA.key:ro"
  #   ports:
  #     - "${RABBITMQ_15671_PORT}:15671"
  #     - "${RABBITMQ_15672_PORT}:15672"
  #     - "${RABBITMQ_5671_PORT}:5671"
  #     - "${RABBITMQ_5672_PORT}:5672"
  #   networks:
  #     - mba-lumen-AG

networks:
  mba-lumen-AG:
    driver: bridge
