version: "3.8"
services:
  # PHP service
  app:
    build: ./docker
    container_name: lumen-app
    working_dir: /var/www/
    volumes:
      - ./src:/var/www
      - ./docker/php-fpm/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./docker/php-fpm/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker/php-fpm/php-fpm.d/www.conf:/usr/local/etc/php-fpm/www.conf
      - ./logs/php-fpm/php-fpm.log:/var/log/php-fpm.log
    networks:
      - mba-lumen-AG

  # MySQL database service
  db:
    image: mysql:5.7
    container_name: lumen-db
    ports:
      - "3307:3306"
    command: mysqld --user=root
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    env_file:
      - ./.env
    networks:
      - mba-lumen-AG

  # Nginx service
  nginx:
    image: nginx:alpine
    container_name: lumen-nginx
    ports:
      - 8888:80
      - 8001:81
      - 8002:82
    volumes:
      - ./src:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ./logs/nginx/access_log.log:/var/log/nginx/access_log.log
      - ./logs/nginx/error.log:/var/log/nginx/error.log
    networks:
      - mba-lumen-AG

  # Cache Redis
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - mba-lumen-AG

  # GUI Manage MySQL
  adminer:
    image: adminer:latest
    container_name: lumen-adminer
    environment:
      ADMINER_DEFAULT_SERVER: db
    restart: always
    ports:
      - 8080:8080
    networks:
      - mba-lumen-AG

  # GUI Manage Docker
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    networks:
      - mba-lumen-AG

  # Test Mail
  mailhog:
    image: mailhog/mailhog
    logging:
      driver: 'none'  # disable saving logs
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui
    networks:
      - mba-lumen-AG


networks:
  mba-lumen-AG:
    driver: bridge
