version: "3.8"
services:
  # PHP service
  app:
    build: ./docker
    container_name: lumen-app
    working_dir: /var/www/
    volumes:
      - ./src:/var/www
    networks:
      - app-network

  # MySQL database service
  db:
    image: mysql:5.7
    container_name: lumen-db
    ports:
      - "3307:3306"
    command: mysqld --user=root
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    env_file:
      - ./.env
    networks:
      - app-network

  # Nginx service
  nginx:
    image: nginx:alpine
    container_name: lumen-nginx
    ports:
      - 8888:80
      - 8001:81
      - 8002:82
    volumes:
      - ./src:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  # GUI Manage MySQL
  adminer:
    image: adminer:latest
    container_name: lumen-adminer
    environment:
      ADMINER_DEFAULT_SERVER: db
    restart: always
    ports:
      - 8080:8080
    networks:
      - app-network

  # GUI Manage Docker
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    networks:
      - app-network

  # Test Mail
  mailhog:
    image: mailhog/mailhog
    logging:
      driver: 'none'  # disable saving logs
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui
    networks:
      - app-network


networks:
  app-network:
    driver: bridge
